esphome:
  name: van_sensor_inputs
  includes:
    
esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "fox"
  password: "12345678and"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hvac Fallback Hotspot"
    password: "aFFcyPK3GxQA"
sensor:
  - platform: adc
    pin: 34
    id: freshwater_adc
    name: "Freshwater Tank ADC"
    attenuation: 11db
    update_interval: 2s

  - platform: tank_level_sensor
    id: freshwater_level_sensor
    name: "Freshwater Tank Level"
    adc_sensor: freshwater_adc
    output_pin: 5
    
    update_interval: 12s
    tank_levels:
      - voltage: 1
        percent_full: 0
      - voltage: 1.140
        percent_full: 25
      - voltage: 1.28
        percent_full: 50
      - voltage: 1.54
        percent_full: 75
      - voltage: 1.9
        percent_full: 100