# dallas.yaml - temp sensors
dallas:
  - pin: 23
    update_interval: 5s
sensor:
# Coolant Temp
  - platform: dallas
    address: 0x683c01f096a08e28
    name: "Temp Coolant"
    id: temp_coolant
  - platform: dallas
    address: 0x923c01d07504bc28
    name: "Temp Freshwater"
    id: temp_freshwater
#outside temp
  - platform: dallas
    address: 0x5f3c01d07581f428
    name: "Temp Outside"
    id: temp_outside
    
  - platform: dallas
    address: 0xd100000cf3191328
    name: "Temp HW Recirculator" 
    id: temp_hw_recirc

  - platform: dallas
    address: 0x593c01d075049028
    name: "Temp Garage"
    id: temp_garage
# house battery
  - platform: dallas
    address: 0x663c01d0753c9728
    name: "Temp House Battery"
    id: temp_house_battery

# new
  - platform: dallas
    address:  0x573c01f09685b528
    name: "Temp Attic"
    id: temp_attic

  - platform: dallas
    address: 0x1e3c01f096a98928
    name: "Temp Refrigerator Cabinet"
    id: temp_refrigerator_cabinet

