sx1509:
  - id: sx1509_hub
    address: 0x3E
   

switch: 
#sx1509 outputs
  - platform: gpio
    name: "Battery Heater"
    id: sw_battery_heater
    pin:
      sx1509: sx1509_hub
      number: 11
      mode:
        output: true
      inverted: false
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Inverter"
    id: "sw_inverter"
    pin:
      sx1509: sx1509_hub
      number: 13
      mode:
        output: true
      inverted: false
    on_turn_on:
    - delay: 250ms
    - switch.turn_off: sw_inverter


  - platform: template
    name: "Enable Inverter"
    lambda: |-
      if (id(input_inverter_enabled).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: sw_inverter
    turn_off_action:
      - switch.turn_on: sw_inverter
    
  - platform: gpio
    name: "Diesel Heater"
    pin:
      sx1509: sx1509_hub
      number: 14
      mode:
        output: true
      inverted: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Audio"
    id: sw_audio
    pin:
      sx1509: sx1509_hub
      number: 15
      mode:
        output: true
      inverted: false
  
  - platform: output
    name: "Water Pump"
    id: sw_water_pump
    output: sx_01
      

  - platform: gpio
    name: "Valve Water Heater"
    id: sw_valve_water_heater
    pin: 32

  - platform: gpio
    name: "Valve Rear Heater"
    id: sw_valve_rear_heater
    pin: 33
    inverted: true

  - platform: gpio
    name: "Valve HW Bypass"
    id: sw_valve_hw_bypass
    restore_mode: ALWAYS_OFF
    pin: 
      number: 18
      inverted: true
      
    on_turn_on:
    - lambda: |- 
        id(water_flow_meter).pause_total(true);
    - delay: 10s
    - switch.turn_off: sw_valve_hw_bypass
    
    on_turn_off:
    - lambda: |- 
        id(water_flow_meter).pause_total(false);

  - platform: gpio
    name: "Valve Coolant Recirculator"
    pin: 5



    
output: 
   # sx1509 
  - platform: sx1509
    id: sx_00
    sx1509_id: sx1509_hub   
    pin: 0
    inverted: true
    min_power: .0001
    max_power: 1
    zero_means_zero: true
    logarithmic: false
    frequency: 3

  - platform: sx1509
    id: sx_01
    sx1509_id: sx1509_hub
    pin: 1
    inverted: true
   

  - platform: sx1509
    id: sx_02
    pin: 2
    sx1509_id: sx1509_hub
    inverted: true
    min_power: 0
    max_power: 1
    zero_means_zero: true
    logarithmic: false
    frequency: 3

  - platform: sx1509
    id: sx_03
    sx1509_id: sx1509_hub
    pin: 3
    inverted: true
    min_power: 0
    max_power: 1
    zero_means_zero: true
    logarithmic: false
    frequency: 3

  - platform: sx1509
    sx1509_id: sx1509_hub
    id: sx_04
    pin: 4
    inverted: true
    min_power: 0.0001
    max_power: 1
    zero_means_zero: true
    logarithmic: false
    frequency: 7

#porch left
  - platform: sx1509
    sx1509_id: sx1509_hub
    id: sx_05
    pin: 5
    inverted: true
    min_power: 0.003
    max_power: 1
    zero_means_zero: true
    logarithmic: true
    frequency: 3
#porch rigth
  - platform: sx1509
    sx1509_id: sx1509_hub
    id: sx_06
    pin: 6
    inverted: true
    min_power: 0.003
    max_power: 1
    zero_means_zero: true
    logarithmic: true
    frequency: 3

  - platform: sx1509
    sx1509_id: sx1509_hub
    id: sx_07
    pin: 7
    inverted: true
    min_power: 0
    max_power: 1
    zero_means_zero: true
    logarithmic: false
    frequency: 3

  - platform: sx1509
    sx1509_id: sx1509_hub
    id: sx_08
    pin: 8
    inverted: true
    min_power: 0
    max_power: 1
    zero_means_zero: true
    logarithmic: false
    frequency: 3

  - platform: sx1509
    sx1509_id: sx1509_hub
    id: sx_09
    pin: 9
    inverted: true
    min_power: 0
    max_power: 1
    frequency: 3
    zero_means_zero: true
    logarithmic: false

  - platform: sx1509
    sx1509_id: sx1509_hub
    id: sx_10
    pin: 10
    inverted: true
    min_power: 0
    max_power: 1
    zero_means_zero: true
    logarithmic: false
    frequency: 3


  - platform: sx1509
    sx1509_id: sx1509_hub
    id: sx_11
    pin: 11
    inverted: true
    

# sx 12 is input

# 13- 15 are photorelays




#esp32 gpio
  - platform: ledc
    frequency: "29296Hz"
    min_power: .29
    pin: 19
    id: hbridge_1
    zero_means_zero : true
   
    # this is a high-side switch.  It switches 12v input provided through adjacent connector pin
  - platform: gpio
    id: highside_switch_1  
    pin: 15


   
light: 
  - platform: monochromatic
    name: "Lights Rear Flood"
    id: light_rear_flood
    output: sx_00
    gamma_correct: 0
    effects:
    - strobe:
          colors:
            - state: true
              brightness: 100%
              duration: 10ms
            - state: false
              duration: 50ms
  
  - platform: monochromatic
    name: "Lights Bed"
    id: light_bed
    output: sx_02
    gamma_correct: 1.1

  - platform: monochromatic
    name: "Button Backlight"
    id: light_button
    output: sx_03
    gamma_correct: 1.1

  - platform: monochromatic
    name: "Lights Cab"
    id: light_cab
    output: sx_04
    gamma_correct: 0

  - platform: monochromatic
    name: "Lights Porch Right"
    id: light_porch_right
    output: sx_05
    gamma_correct: 1.1
    effects:
    - strobe:
          colors:
            - state: true
              brightness: 100%
              duration: 10ms
            - state: false
              duration: 50ms

  - platform: monochromatic
    name: "Lights Porch Left"
    id: light_porch_left
    output: sx_06
    gamma_correct: 1.1
    effects:
    - strobe:
          colors:
            - state: true
              brightness: 100%
              duration: 10ms
            - state: false
              duration: 50ms

  - platform: monochromatic
    name: "Lights Garage"
    id: light_garage
    output: sx_07
    gamma_correct: 1.1

  - platform: monochromatic
    name: "Lights Hall"
    id: light_hall
    output: sx_08
    gamma_correct: 1.1

  - platform: monochromatic
    name: "Lights Kitchen"
    id: light_kitchen
    output: sx_09
    gamma_correct: 1.1

  - platform: monochromatic
    name: "Lights Shower"
    id: light_shower
    output: sx_10
    gamma_correct: 1.1

binary_sensor:
  - platform: gpio
    name: "Button Kitchen Outside"
    id: btn_kitchen_outside
    pin: 
      number: 27
      mode:
        input: true
        pullup: true
    filters:
      - invert:
      - delayed_on: 10ms
    on_click: 
      min_length: 10ms
      max_length: 350ms
      then:
      - if:
          condition:
            - light.is_off: light_porch_right
          then:
            - light.turn_on:
                id: light_porch_right
                brightness: .8
          else:
            - light.turn_off: light_porch_right

    on_press:
      then:
        - if:
            condition:
              light.is_off: light_porch_right
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: btn_kitchen_outside
                  then:
                    - light.dim_relative:
                        id: light_porch_right
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: btn_kitchen_outside
                      - light.is_on: light_porch_right
                  then:
                    - light.dim_relative:
                        id: light_porch_right
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    
     
  - platform: gpio
    name: "Button Kitchen Master"
    id: btn_master
    pin: 
      number: 13
      mode:
        input: true
        pullup: true
        
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click: 
      min_length: 10ms
      max_length: 350ms
      then:
      - if:
          condition:  # change to 1  4 6 8
            or:
            - light.is_off: light_bed
            - light.is_off: light_hall
            - light.is_off: light_kitchen
            - light.is_off: light_shower
           
          then:
            - light.turn_on: 
                id: light_hall
                brightness: 80%

            - light.turn_on: 
                id: light_kitchen
                brightness: 80%

            - light.turn_on: 
                id: light_shower
                brightness: 80%

            - light.turn_on: 
                id: light_bed
                brightness: 80%

            
          else:
            - light.turn_off: light_hall
            - light.turn_off: light_kitchen
            - light.turn_off: light_shower
            - light.turn_off: light_bed
            
    on_press:
      then:
        - if:
            condition:
              light.is_off: light_hall
            then:
              - delay: 0.25s
              - while:
                  condition:
                    binary_sensor.is_on: btn_master
                  then:
                    - light.dim_relative:
                        id: light_hall
                        relative_brightness: 5%
                        transition_length: 0.1s
                  
                    - light.dim_relative:
                        id: light_kitchen
                        relative_brightness: 5%
                        transition_length: 0.1s
                    
                    - light.dim_relative:
                        id: light_shower
                        relative_brightness: 5%
                        transition_length: 0.1s
                    
                    - light.dim_relative:
                        id: light_bed
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.25s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: btn_master
                      - light.is_on: light_hall
                  then:
                    - light.dim_relative:
                        id: light_hall
                        relative_brightness: -5%
                        transition_length: 0.1s
                    
                    - light.dim_relative:
                        id: light_kitchen
                        relative_brightness: -5%
                        transition_length: 0.1s
                    
                    - light.dim_relative:
                        id: light_shower
                        relative_brightness: -5%
                        transition_length: 0.1s
                    
                    - light.dim_relative:
                        id: light_bed
                        relative_brightness: -5%
                        transition_length: 0.1s

                    - delay: 0.1s
  - platform: gpio
    name: "Button Kitchen"
    id: btn_kitchen
    pin: 
      number: 14
      mode:
        input: true
        pullup: true
    filters:
      - invert:
      - delayed_on: 10ms
    on_click: 
      min_length: 10ms
      max_length: 350ms
      then:
      - if:
          condition:
            - light.is_off: light_hall
            - light.is_off: light_kitchen
          then:
            - light.turn_on:
                id: light_hall
                
            - light.turn_on:
                id: light_kitchen
               
          else:
            - light.turn_off: light_hall
            - light.turn_off: light_kitchen
    on_press:
      then:
        - if:
            condition:
              - light.is_off: light_hall
              - light.is_off: light_kitchen

            then:
              - delay: 0.25s
              - light.turn_on: light_hall
              - light.turn_on: light_kitchen
              - while:
                  condition:
                    binary_sensor.is_on: btn_kitchen
                  then:
                    - light.dim_relative:
                        id: light_hall
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - light.dim_relative:
                        id: light_kitchen
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    
            else:
              - delay: 0.25s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: btn_kitchen
                      - light.is_on: light_hall
                  then:
                    - light.dim_relative:
                        id: light_hall
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - light.dim_relative:
                        id: light_kitchen
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
  
  - platform: gpio
    name: "Button Shower Light"
    id: btn_shower_light
    pin: 
      number: 12
      mode:
        input: true
        pullup: true
    filters:
      - invert:
      - delayed_on: 10ms
    on_click: 
      min_length: 10ms
      max_length: 350ms
      then:
        light.toggle: light_shower
    on_press:
      then:
        - if:
            condition:
              light.is_off: light_shower
            then:
              - delay: 0.5s
              - light.turn_on: light_shower
              - while:
                  condition:
                    binary_sensor.is_on: btn_shower_light
                  then:
                    - light.dim_relative:
                        id: light_shower
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: btn_shower_light
                      - light.is_on: light_shower
                  then:
                    - light.dim_relative:
                        id: light_shower
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
  - platform: gpio
    name: "Button Shower Fan"
    id: btn_shower_fan
    pin: 
      number: 4
      mode:
        input: true
        pullup: true
    on_click:
      min_length: 10ms
      max_length: 450ms
      then:
        fan.toggle: shower_fan
    filters:
      - invert:
      - delayed_on: 10ms

  - platform: gpio
    name: "Button Bed"
    id: btn_bed
    pin: 
      number: 0
      mode:
        input: true
        pullup: true
    filters:
      - invert:
      - delayed_on: 10ms
    on_click: 
          min_length: 10ms
          max_length: 350ms
          then:
          - if:
              condition:
                - light.is_off: light_bed
               
              then:
                - light.turn_on:
                    id: light_bed                
              else:
                - light.turn_off: light_bed
    on_press:
        then:
          - if:
              condition:
                light.is_off: light_bed
              then:
                - delay: 0.25s
                - while:
                    condition:
                      binary_sensor.is_on: btn_bed
                    then:
                      - light.dim_relative:
                          id: light_bed
                          relative_brightness: 5%
                          transition_length: 0.1s
                      - delay: 0.1s
                      
              else:
                - delay: 0.25s
                - while:
                    condition:
                      and:
                        - binary_sensor.is_on: btn_bed
                        - light.is_on: light_bed
                    then:
                      - light.dim_relative:
                          id: light_bed
                          relative_brightness: -5%
                          transition_length: 0.1s
                      - delay: 0.1s
  - platform: gpio
    name: "Button Sink"
    id: btn_sink
    pin: 
      number: 2
      mode:
        input: true
        pullup: true
    filters:
      - invert:
      - delayed_on: 10ms
    on_click:
      min_length: 10ms
      max_length: 450ms
      then:
        if:
          condition:
            switch.is_on: sw_valve_hw_bypass
          then:
            - switch.turn_off: sw_valve_hw_bypass
          else:
            - switch.turn_on: sw_valve_hw_bypass

  - platform: gpio
    name: "Inverter Enabled"
    id: input_inverter_enabled
    pin: 
      sx1509: sx1509_hub
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
sensor:

  - platform: duty_cycle
    name: "Cab Light On"
    id: input_cab_light
    pin: 
      number: 36
      mode:
        input: true
      inverted: true
