substitutions:
  device_name: "Dinette Light"
  device_id: dinette_light
  button_id: btn_${device_id}
  wifi_name: "dinettelight"
  password: "govango!"

esphome:
  name: ${wifi_name}
  platform: ESP8266
  board: esp01_1m


wifi:
  ssid: "vango-inside"
  password: $password
  fast_connect: on
  power_save_mode: none
  output_power: 10.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ap_timeout: 5min
    ssid: "${device_name} hardware hotspot"

captive_portal:
logger:
api:
ota:

sensor:
  - platform: adc
    pin: A0
    name: "${device_name} adc"
    update_interval: 5s
    accuracy_decimals: 4
    id: ${device_id}_current_raw
    internal: true
  - platform: template
    name: "${device_name} power"
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    lambda: return id(${device_id}_current_raw).state;
    filters:
      - calibrate_linear:
        - 0.4000 -> 0.0
        - 0.4043 -> 0.14
        - 0.4053 -> 0.20
      - multiply: 12 # 12V lamp

binary_sensor:
  - platform: gpio
    name: "Button ${device_name}"
    id: ${button_id}
    pin: 
      number: GPIO5
      mode:
        input: true
        #be sure not to enable pullup- shelly must have it built-in
    
    filters:
      - delayed_on: 10ms
    on_click: 
      min_length: 10ms
      max_length: 350ms
      then:
      - if:
          condition:
            - light.is_off: ${device_id}
          then:
            - light.turn_on:
                id: ${device_id}
                brightness: .8
          else:
            - light.turn_off: ${device_id}

    on_press:
      then:
        - if:
            condition:
              light.is_off: ${device_id}
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: ${button_id}
                  then:
                    - light.dim_relative:
                        id: ${device_id}
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: ${button_id}
                      - light.is_on: ${device_id}
                  then:
                    - light.dim_relative:
                        id: ${device_id}
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    

light:
  - platform: rgbw
    id: ${device_id}
    name: ${device_name}
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: esp8266_pwm
    pin: GPIO14 # default pin is 12
    frequency: 25000 Hz
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 25000 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO4 # default pin is 14
    frequency: 25000 Hz
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO12 #default pin is 4
    frequency: 25000 Hz
    id: pwm_w