#sensors
sensor:
  - platform: adc
    pin: 34
    id: freshwater_adc
    name: "Freshwater Tank ADC"
    attenuation: 2.5db
    update_interval: 5s
    # filters:
    # - sliding_window_moving_average:
    #     window_size: 15
    #     send_every: 5

  - platform: tank_level_sensor
    id: freshwater_level_sensor
    name: "Freshwater Tank Level"
    adc_sensor: freshwater_adc
    voltage_high: 1.2
    voltage_low: 1.04
    invert: false
    auto_range: false
    tank_capacity: 25.0
    update_interval: 5s
    percent_full:
      id: sensor_percent_fresh
      name: "Freshwater Percent Left"
    amount_left:
      id: sensor_amt_left
      name: "Freshwater Remaining"
 
  - platform: adc
    pin: 35
    id: graywater_adc
    name: "Graywater Tank ADC"
    attenuation: 2.5db
    update_interval: 5s

  - platform: tank_level_sensor
    id: graywater_level_sensor
    name: "Graywater Tank Level"
    adc_sensor: graywater_adc
    tank_capacity: 20.0
    voltage_high: 1.2
    voltage_low: 1
    invert: false
    auto_range: false
    update_interval: 5s
    percent_full:
      id: sensor_percent_grey
      name: "Graywater Percent Full"
    amount_left:
      id: sensor_amt_left_grey
      name: "Greywater Used"
 
