substitutions:
  name: "vango"
  lower_devicename: $name
  devicename: "Vango"
  config_version: "v2022.11.18.001"
  # wifi_fast_connect: "false"
  # wifi_reboot_timeout: 0s
  accuracy: "2"
  password: "govango!"
  device_verbose_name: "Vango integration hardware"

esphome:
  name: $name

esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  # baud_rate: 115200
  level: DEBUG
  logs:
    sensor: WARN
    adc: WARN
    gpio.binary_sensor: WARN
    light: WARN
    mpu6050: WARN
    pulse_counter: WARN
    sx1509: WARN
    text_sensor: WARN
    dallas.sensor: WARN
    bme280.sensor: WARN
    victron_smart_shunt: ERROR
    uart_debug: WARN
    ledc: WARN
    climate: WARN
    fan: WARN
    tank_level.sensor: WARN
    monochromatic: WARN

# Enable Home Assistant API
api:
  password: $password

ota:
  - platform: esphome
    password: $password

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true
    frequency: 50kHz

packages:
  system: !include system.yaml
  dallas: !include dallas.yaml
  mpu6050: !include mpu6050.yaml
  bme280.yaml: !include bme280.yaml
  tanklevelsensor: !include tanklevelsensor.yaml
  waterflowsensor: !include waterflowsensor.yaml
  gpio: !include gpio.yaml
  victron: !include victron_smartshunt.yaml
  climate: !include climate.yaml
